apiVersion: batch/v1
kind: Job
metadata:
  name: inbox-independent-exapmle
spec:
  ttlSecondsAfterFinished: 90
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: task
        image: busybox
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
          - python3 download_from_prp.py ...(other commands)
        env:
          - name: UUID
            value: $UUID
        resources: 
          requests: 
            cpu: "100m" 
            memory: "100Mi" 
          limits: 
            cpu: "1" 
            memory: "1Gi"
      restartPolicy: Never

